services:

  api:
    build: .
    image: qchat-api
    env_file:
      - .env
    volumes:
      - .:/qchat:ro
      - .env:/qchat/.env:ro
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - qchat_pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  qchat_pg_data:
