name: "⚒️ Deploy image to GHCR"

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build Inventory Image
        run: |
          docker build . --tag geotribu/qchat-api:$(poetry version -s) --tag geotribu/qchat-api:latest
          docker push ghcr.io/geotribu/qchat-api:$(poetry version -s)
          docker push ghcr.io/geotribu/qchat-api:latest
